
package ojeksoap.controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "History", targetNamespace = "http://controller.ojeksoap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface History {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hideHistoryDriverById", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.HideHistoryDriverById")
    @ResponseWrapper(localName = "hideHistoryDriverByIdResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.HideHistoryDriverByIdResponse")
    @Action(input = "http://controller.ojeksoap/History/hideHistoryDriverByIdRequest", output = "http://controller.ojeksoap/History/hideHistoryDriverByIdResponse")
    public String hideHistoryDriverById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPreviousOrderByUsername", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.GetPreviousOrderByUsername")
    @ResponseWrapper(localName = "getPreviousOrderByUsernameResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.GetPreviousOrderByUsernameResponse")
    @Action(input = "http://controller.ojeksoap/History/getPreviousOrderByUsernameRequest", output = "http://controller.ojeksoap/History/getPreviousOrderByUsernameResponse")
    public String getPreviousOrderByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hideHistoryByUsername", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.HideHistoryByUsername")
    @ResponseWrapper(localName = "hideHistoryByUsernameResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.HideHistoryByUsernameResponse")
    @Action(input = "http://controller.ojeksoap/History/hideHistoryByUsernameRequest", output = "http://controller.ojeksoap/History/hideHistoryByUsernameResponse")
    public String hideHistoryByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDriverHistoryByUsername", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.GetDriverHistoryByUsername")
    @ResponseWrapper(localName = "getDriverHistoryByUsernameResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.GetDriverHistoryByUsernameResponse")
    @Action(input = "http://controller.ojeksoap/History/getDriverHistoryByUsernameRequest", output = "http://controller.ojeksoap/History/getDriverHistoryByUsernameResponse")
    public String getDriverHistoryByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
