
package ojeksoap.controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Location", targetNamespace = "http://controller.ojeksoap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Location {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editPreferredLocation", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.EditPreferredLocation")
    @ResponseWrapper(localName = "editPreferredLocationResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.EditPreferredLocationResponse")
    @Action(input = "http://controller.ojeksoap/Location/editPreferredLocationRequest", output = "http://controller.ojeksoap/Location/editPreferredLocationResponse")
    public String editPreferredLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPreferredLocation", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.GetPreferredLocation")
    @ResponseWrapper(localName = "getPreferredLocationResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.GetPreferredLocationResponse")
    @Action(input = "http://controller.ojeksoap/Location/getPreferredLocationRequest", output = "http://controller.ojeksoap/Location/getPreferredLocationResponse")
    public String getPreferredLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPreferredLocation", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.AddPreferredLocation")
    @ResponseWrapper(localName = "addPreferredLocationResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.AddPreferredLocationResponse")
    @Action(input = "http://controller.ojeksoap/Location/addPreferredLocationRequest", output = "http://controller.ojeksoap/Location/addPreferredLocationResponse")
    public String addPreferredLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePreferredLocation", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.DeletePreferredLocation")
    @ResponseWrapper(localName = "deletePreferredLocationResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.DeletePreferredLocationResponse")
    @Action(input = "http://controller.ojeksoap/Location/deletePreferredLocationRequest", output = "http://controller.ojeksoap/Location/deletePreferredLocationResponse")
    public String deletePreferredLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
