
package ojeksoap.controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderImplService", targetNamespace = "http://controller.ojeksoap/", wsdlLocation = "http://localhost:8002/order?wsdl")
public class OrderImplService
    extends Service
{

    private final static URL ORDERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERIMPLSERVICE_EXCEPTION;
    private final static QName ORDERIMPLSERVICE_QNAME = new QName("http://controller.ojeksoap/", "OrderImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/order?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERIMPLSERVICE_WSDL_LOCATION = url;
        ORDERIMPLSERVICE_EXCEPTION = e;
    }

    public OrderImplService() {
        super(__getWsdlLocation(), ORDERIMPLSERVICE_QNAME);
    }

    public OrderImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERIMPLSERVICE_QNAME, features);
    }

    public OrderImplService(URL wsdlLocation) {
        super(wsdlLocation, ORDERIMPLSERVICE_QNAME);
    }

    public OrderImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERIMPLSERVICE_QNAME, features);
    }

    public OrderImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Order
     */
    @WebEndpoint(name = "OrderImplPort")
    public Order getOrderImplPort() {
        return super.getPort(new QName("http://controller.ojeksoap/", "OrderImplPort"), Order.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Order
     */
    @WebEndpoint(name = "OrderImplPort")
    public Order getOrderImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.ojeksoap/", "OrderImplPort"), Order.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERIMPLSERVICE_EXCEPTION!= null) {
            throw ORDERIMPLSERVICE_EXCEPTION;
        }
        return ORDERIMPLSERVICE_WSDL_LOCATION;
    }

}
