
package ojeksoap.controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Order", targetNamespace = "http://controller.ojeksoap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Order {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.CreateOrderResponse")
    @Action(input = "http://controller.ojeksoap/Order/createOrderRequest", output = "http://controller.ojeksoap/Order/createOrderResponse")
    public String createOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchDriver", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.SearchDriver")
    @ResponseWrapper(localName = "searchDriverResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.SearchDriverResponse")
    @Action(input = "http://controller.ojeksoap/Order/searchDriverRequest", output = "http://controller.ojeksoap/Order/searchDriverResponse")
    public String searchDriver(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
