
package ojeksoap.controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Users", targetNamespace = "http://controller.ojeksoap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Users {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.CreateUserResponse")
    @Action(input = "http://controller.ojeksoap/Users/createUserRequest", output = "http://controller.ojeksoap/Users/createUserResponse")
    public String createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.UpdateUserResponse")
    @Action(input = "http://controller.ojeksoap/Users/updateUserRequest", output = "http://controller.ojeksoap/Users/updateUserResponse")
    public String updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserRatingAndVotes", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.GetUserRatingAndVotes")
    @ResponseWrapper(localName = "getUserRatingAndVotesResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.GetUserRatingAndVotesResponse")
    @Action(input = "http://controller.ojeksoap/Users/getUserRatingAndVotesRequest", output = "http://controller.ojeksoap/Users/getUserRatingAndVotesResponse")
    public String getUserRatingAndVotes(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByUsername", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.GetUserByUsername")
    @ResponseWrapper(localName = "getUserByUsernameResponse", targetNamespace = "http://controller.ojeksoap/", className = "ojeksoap.controller.GetUserByUsernameResponse")
    @Action(input = "http://controller.ojeksoap/Users/getUserByUsernameRequest", output = "http://controller.ojeksoap/Users/getUserByUsernameResponse")
    public String getUserByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
