
package servisojek.identityservice.controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SessionSOAPImplService", targetNamespace = "http://controller.IdentityService.servisojek/", wsdlLocation = "http://localhost:8001/session/validate?wsdl")
public class SessionSOAPImplService
    extends Service
{

    private final static URL SESSIONSOAPIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SESSIONSOAPIMPLSERVICE_EXCEPTION;
    private final static QName SESSIONSOAPIMPLSERVICE_QNAME = new QName("http://controller.IdentityService.servisojek/", "SessionSOAPImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8001/session/validate?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SESSIONSOAPIMPLSERVICE_WSDL_LOCATION = url;
        SESSIONSOAPIMPLSERVICE_EXCEPTION = e;
    }

    public SessionSOAPImplService() {
        super(__getWsdlLocation(), SESSIONSOAPIMPLSERVICE_QNAME);
    }

    public SessionSOAPImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SESSIONSOAPIMPLSERVICE_QNAME, features);
    }

    public SessionSOAPImplService(URL wsdlLocation) {
        super(wsdlLocation, SESSIONSOAPIMPLSERVICE_QNAME);
    }

    public SessionSOAPImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SESSIONSOAPIMPLSERVICE_QNAME, features);
    }

    public SessionSOAPImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionSOAPImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SessionSOAP
     */
    @WebEndpoint(name = "SessionSOAPImplPort")
    public SessionSOAP getSessionSOAPImplPort() {
        return super.getPort(new QName("http://controller.IdentityService.servisojek/", "SessionSOAPImplPort"), SessionSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionSOAP
     */
    @WebEndpoint(name = "SessionSOAPImplPort")
    public SessionSOAP getSessionSOAPImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.IdentityService.servisojek/", "SessionSOAPImplPort"), SessionSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SESSIONSOAPIMPLSERVICE_EXCEPTION!= null) {
            throw SESSIONSOAPIMPLSERVICE_EXCEPTION;
        }
        return SESSIONSOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
